Додає футер
ukrwebprom/FoodSta pull request #10
Opened 2022-10-30 14:44 UTC by nastyawaks

Потрібно змінити налаштування фонових зображень, вони не відповідають макету
Навігація в таблет та декстоп не відцентрована по вертикалі

2022-10-30 16:50 UTC, ukrwebprom commented on src/sass/_footer.scss
>  .footer {
после того как сонтейнер перенесли внутрь секций, эти стили с фоновыми картинками нужно назначить не для  footer а для footer-container

2022-10-30 16:54 UTC, ukrwebprom commented on src/sass/_footer.scss
> +    width: 320px;
это не нужно. ширина контейнера для мобильного устройства 480пикс или 100% ширины экрана если экран уже 480пикс.

2022-10-30 16:57 UTC, ukrwebprom commented on src/sass/_footer.scss
> +.footer-container {
контейнеру нужно добавить левый и правый паддинг
16пикс для десктопа, 32 пикс для планшета и 20 пикс для телефона

2022-10-30 23:07 UTC, nastyawaks commented on src/sass/_footer.scss
> +    width: 320px;
Убрала, но тогда меню тянется по ширине контейнера и форма с кнопкой тоже. Можно ограничить размер поля формы, но смотрится странно

2022-10-30 23:08 UTC, nastyawaks commented on src/sass/_footer.scss
> +.footer-container {
там класс “container footer-container”, поэтому паддинги есть

2022-10-31 10:58 UTC, ukrwebprom commented on src/sass/_footer.scss
> +      background-size: 100% auto, 203px 365px;
background-size можно не указывать. картинки все нужных размеров и они будут отображаться в оригинальном размере.

2022-10-31 11:00 UTC, nastyawaks commented on src/sass/_footer.scss
> +      background-size: 100% auto, 203px 365px;
Пробовала не указывать и тогда 2х становятся очень большими

2022-10-31 12:13 UTC, ukrwebprom requested changes
- меню не отцентровано по вертикали относительно логотипа
- у тебя заданы нижние отступы и в .footer-sub и в .footer__wrap. надо оставить только .footer__wrap и прописать для разных размеров экрана.
- в целом, я бы сделал чуть по другому - у тебя сейчас в .footer__wrap 3 дочерних элемента, поэтому их сложно позиционировать на разных размерах. что если сделать еще одну обертку в которой будет логотип и меню, и отдельно, вторым элементом .footer-sub. думаю так будет проще

2022-10-31 12:19 UTC, ukrwebprom commented on src/sass/_footer.scss
> +      background-size: 100% auto, 203px 365px;
да, ты права. но тогда надо убрать 100% auto чтобы не тянулось на таблетке. я сейчас закину новую картинку без обрезанного яблока справа

2022-10-31 12:26 UTC, ukrwebprom commented on src/sass/_footer.scss
> +      background-size: 100% auto, 203px 365px;
есть. обнови майн. сейчас для планшета есть нижнее изображение (не обрезанное) и отдельно правое

2022-10-31 12:46 UTC, nastyawaks commented on src/sass/_footer.scss
> +      background-size: 100% auto, 203px 365px;
Я вчера закинула нижнее и правое для таблет, т.к ранее там была одна, поэтому смогла отцентровать их, разве задать размеры будет ошибкой?

2022-10-31 13:04 UTC, ukrwebprom commented on src/sass/_footer.scss
> +      background-size: 100% auto, 203px 365px;
нет, но у тебя в планшетной версии было 100% и нижняя картинка тянулась

2022-10-31 13:10 UTC, ukrwebprom commented on src/sass/_footer.scss
> +      background-size: 100% auto, 203px 365px;
по поводу конфликта, когда будешь отправлять pull request и гит выдаст конфликт, там в выпадающем списке выбери свои варианты

2022-10-31 19:12 UTC, merged